# Generated by Django 5.0.6 on 2024-06-21 18:46

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_pic', models.ImageField(blank=True, null=True, upload_to=posts.models.user_uploads_path)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('Strategy', 'Strategy'), ('Party', 'Party'), ('Cooperative', 'Cooperative'), ('Deck-Building', 'Deck-Building'), ('Role-Playing', 'Role-Playing'), ('Abstract', 'Abstract'), ('Family', 'Family'), ('Thematic', 'Thematic'), ('Word', 'Word'), ('Dice', 'Dice'), ('Card', 'Card'), ('Miniatures', 'Miniatures'), ('Wargame', 'Wargame'), ('Legacy', 'Legacy'), ('Tile-Laying', 'Tile-Laying'), ('Economic', 'Economic'), ('Deduction', 'Deduction'), ('Bluffing', 'Bluffing'), ('Trivia', 'Trivia'), ("Children's", "Children's")], default='Strategy', max_length=50)),
                ('visits_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike'), ('None', 'None')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_dislikes', to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
